package main;

import java.util.Scanner;

public class HelloWorld {
   public HelloWorld() {
   }

   public static void main(String[] var0) {
      System.out.println("Hello, World!");
      Scanner var1 = new Scanner(System.in);
      System.out.print("Enter a number: ");
      int var2 = var1.nextInt();
      int var3 = var2 * 2;
      System.out.println("Double of " + var2 + " is " + var3);
      var1.close();
   }
}
